# Generated by Django 2.2 on 2019-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='avatar',
            field=models.ImageField(db_index=True, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='path',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
