# Generated by Django 2.2 on 2019-05-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190522_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(db_index=True, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.ImageField(db_index=True, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='path',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.CreateModel(
            name='BotMessageFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('path', models.FilePathField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BotUserMessage')),
            ],
        ),
    ]
