# Generated by Django 2.2 on 2019-06-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190604_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='full_path',
            field=models.CharField(max_length=255),
        ),
    ]
