# Generated by Django 2.2 on 2019-06-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190605_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='full_path',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
