# Generated by Django 2.2 on 2019-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190605_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFileAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.postfile',),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
